In [1]:
## ipynb for sampling data for expert judgement
import pandas as pd

In [2]:
ALL_DATA_FILE = '/chronos_data/avirinchipur/reasoning_for_psych/expts/responses/expt_gpt-4.dep_list_phq9items_score_classify_editted.csv'
CURRENT_DATA_SAMPLE_FILE = '/chronos_data/avirinchipur/reasoning_for_psych/kjell_prolific/depText_kjell_scoring.csv'

In [3]:
all_data_df = pd.read_csv(ALL_DATA_FILE)
current_data_df = pd.read_csv(CURRENT_DATA_SAMPLE_FILE, encoding='latin1')

In [4]:
print (all_data_df.shape)

(956, 5)

In [5]:
print (current_data_df.shape)

(100, 6)

In [6]:
current_data_df

,user_id,dep_text,PHQ_tot_estimates_a,PHQ_tot_estimates_c,mean_c_a2_fmt,PHQtot3
0,904,I wouldn't say I have been depressed badly. Ho...,5.0,8.0,6.5,7
1,479,I have been depressed these past two weeks. I ...,11.0,20.0,15.5,23
2,442,I am generally happy and content in my life an...,3.0,2.0,2.5,0
3,369,I have been pressed because of the issue of Co...,7.0,6.0,6.5,6
4,774,I am mostly a positive person but I am very em...,7.0,7.0,7.0,13
...,...,...,...,...,...,...
95,480,"The last week has been hard, I have not wanted...",13.0,16.0,14.5,19
96,449,"I would answer this question by saying that, b...",4.0,8.0,6.0,6
97,445,Over the last two weeks i have not felt depres...,3.0,4.0,3.5,5
98,404,I haven not been depressed over the past 2 wee...,2.0,3.0,2.5,19
99,181,I am not depressed and in general do not get d...,3.0,3.0,3.0,0

In [7]:
remaining_data_df = all_data_df[~all_data_df['user_id'].isin(current_data_df['user_id'])]
remaining_data_df.shape

(856, 5)

In [8]:
new_sample = remaining_data_df.sample(n=110, replace=False, random_state=42)[['user_id', 'user_text', 'target_value']]
new_sample

     user_id                                          user_text  target_value
790      810  The wider world issues about Covid 19 depress ...            16
674      693  I have been relatively depressed in the last t...            11
126      127  I have felt quite lonely as I live alone and d...            10
229      230  I will say that am  not depressed, one of the ...             3
419      431  I haven't really been depressed over the last ...             0
..       ...                                                ...           ...
31        32  I have been depressed. I have been sleeping at...            15
577      595  I have felt depressed and it has caused me to ...            14
675      694  I have felt despairing at my social isolation;...            20
536      554  Over the last 2 weeks I have been feeling more...            22
689      709  Yes. Very. I have gone back on SSRIs after hav...            27

[110 rows x 3 columns]

In [9]:
new_sample['PHQ_tot_estimate'] = ''
new_sample

,user_id,user_text,target_value,PHQ_tot_estimate
790,810,The wider world issues about Covid 19 depress ...,16,
674,693,I have been relatively depressed in the last t...,11,
126,127,I have felt quite lonely as I live alone and d...,10,
229,230,"I will say that am not depressed, one of the ...",3,
419,431,I haven't really been depressed over the last ...,0,
...,...,...,...,...
31,32,I have been depressed. I have been sleeping at...,15,
577,595,I have felt depressed and it has caused me to ...,14,
675,694,I have felt despairing at my social isolation;...,20,
536,554,Over the last 2 weeks I have been feeling more...,22,
689,709,Yes. Very. I have gone back on SSRIs after hav...,27,

In [10]:
new_sample = new_sample.rename(columns={'user_text':'dep_text'})
new_sample

,user_id,dep_text,target_value,PHQ_tot_estimate
790,810,The wider world issues about Covid 19 depress ...,16,
674,693,I have been relatively depressed in the last t...,11,
126,127,I have felt quite lonely as I live alone and d...,10,
229,230,"I will say that am not depressed, one of the ...",3,
419,431,I haven't really been depressed over the last ...,0,
...,...,...,...,...
31,32,I have been depressed. I have been sleeping at...,15,
577,595,I have felt depressed and it has caused me to ...,14,
675,694,I have felt despairing at my social isolation;...,20,
536,554,Over the last 2 weeks I have been feeling more...,22,
689,709,Yes. Very. I have gone back on SSRIs after hav...,27,

In [11]:
new_sample[['user_id', 'dep_text', 'PHQ_tot_estimate']].to_csv('./new_sample_for_experts.csv', index=False, encoding='utf-8')

In [13]:
temp_df = pd.merge(all_data_df, current_data_df[['user_id', 'PHQ_tot_estimates_a', 'PHQ_tot_estimates_c']], on='user_id', how='inner')
for phq_estimate_col in ['PHQ_tot_estimates_a', 'PHQ_tot_estimates_c']:
    temp_current_df = temp_df[['user_id', 'user_text', phq_estimate_col]] 
    temp_current_df = temp_current_df.rename(columns={'user_text':'dep_text', phq_estimate_col:'PHQ_tot_estimate'})
    temp_combined_df = pd.concat([temp_current_df, new_sample], axis=0)
    temp_combined_df[['user_id', 'dep_text', 'PHQ_tot_estimate']].to_csv('./new_sample_for_experts_{}.csv'.format(phq_estimate_col), index=False, encoding='utf-8')